// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: synchronizer.proto
// Original file comments:
// proto file for synchronizer 
//
#ifndef GRPC_synchronizer_2eproto__INCLUDED
#define GRPC_synchronizer_2eproto__INCLUDED

#include "synchronizer.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace csce438 {

// The synchronizer service definition.
class SynchService final {
 public:
  static constexpr char const* service_full_name() {
    return "csce438.SynchService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // update user file
    virtual ::grpc::Status SyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::csce438::SyncReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>> AsyncSyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>>(AsyncSyncUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>> PrepareAsyncSyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>>(PrepareAsyncSyncUsersRaw(context, request, cq));
    }
    // update follower file
    virtual ::grpc::Status SyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::csce438::SyncReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>> AsyncSyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>>(AsyncSyncFollowersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>> PrepareAsyncSyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>>(PrepareAsyncSyncFollowersRaw(context, request, cq));
    }
    // update timeline
    virtual ::grpc::Status SyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::csce438::SyncReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>> AsyncSyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>>(AsyncSyncTimelineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>> PrepareAsyncSyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>>(PrepareAsyncSyncTimelineRaw(context, request, cq));
    }
    virtual ::grpc::Status UpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::csce438::SyncReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>> AsyncUpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>>(AsyncUpdateMasterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>> PrepareAsyncUpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>>(PrepareAsyncUpdateMasterRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // update user file
      virtual void SyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // update follower file
      virtual void SyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // update timeline
      virtual void SyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest* request, ::csce438::SyncReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest* request, ::csce438::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void UpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo* request, ::csce438::SyncReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo* request, ::csce438::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>* AsyncSyncUsersRaw(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>* PrepareAsyncSyncUsersRaw(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>* AsyncSyncFollowersRaw(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>* PrepareAsyncSyncFollowersRaw(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>* AsyncSyncTimelineRaw(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>* PrepareAsyncSyncTimelineRaw(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>* AsyncUpdateMasterRaw(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csce438::SyncReply>* PrepareAsyncUpdateMasterRaw(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::csce438::SyncReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>> AsyncSyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>>(AsyncSyncUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>> PrepareAsyncSyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>>(PrepareAsyncSyncUsersRaw(context, request, cq));
    }
    ::grpc::Status SyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::csce438::SyncReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>> AsyncSyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>>(AsyncSyncFollowersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>> PrepareAsyncSyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>>(PrepareAsyncSyncFollowersRaw(context, request, cq));
    }
    ::grpc::Status SyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::csce438::SyncReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>> AsyncSyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>>(AsyncSyncTimelineRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>> PrepareAsyncSyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>>(PrepareAsyncSyncTimelineRaw(context, request, cq));
    }
    ::grpc::Status UpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::csce438::SyncReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>> AsyncUpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>>(AsyncUpdateMasterRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>> PrepareAsyncUpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>>(PrepareAsyncUpdateMasterRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response, std::function<void(::grpc::Status)>) override;
      void SyncUsers(::grpc::ClientContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response, std::function<void(::grpc::Status)>) override;
      void SyncFollowers(::grpc::ClientContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest* request, ::csce438::SyncReply* response, std::function<void(::grpc::Status)>) override;
      void SyncTimeline(::grpc::ClientContext* context, const ::csce438::timelineRequest* request, ::csce438::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo* request, ::csce438::SyncReply* response, std::function<void(::grpc::Status)>) override;
      void UpdateMaster(::grpc::ClientContext* context, const ::csce438::MasterInfo* request, ::csce438::SyncReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>* AsyncSyncUsersRaw(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>* PrepareAsyncSyncUsersRaw(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>* AsyncSyncFollowersRaw(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>* PrepareAsyncSyncFollowersRaw(::grpc::ClientContext* context, const ::csce438::SyncRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>* AsyncSyncTimelineRaw(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>* PrepareAsyncSyncTimelineRaw(::grpc::ClientContext* context, const ::csce438::timelineRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>* AsyncUpdateMasterRaw(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csce438::SyncReply>* PrepareAsyncUpdateMasterRaw(::grpc::ClientContext* context, const ::csce438::MasterInfo& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SyncUsers_;
    const ::grpc::internal::RpcMethod rpcmethod_SyncFollowers_;
    const ::grpc::internal::RpcMethod rpcmethod_SyncTimeline_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateMaster_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // update user file
    virtual ::grpc::Status SyncUsers(::grpc::ServerContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response);
    // update follower file
    virtual ::grpc::Status SyncFollowers(::grpc::ServerContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response);
    // update timeline
    virtual ::grpc::Status SyncTimeline(::grpc::ServerContext* context, const ::csce438::timelineRequest* request, ::csce438::SyncReply* response);
    virtual ::grpc::Status UpdateMaster(::grpc::ServerContext* context, const ::csce438::MasterInfo* request, ::csce438::SyncReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SyncUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SyncUsers() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SyncUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncUsers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncUsers(::grpc::ServerContext* context, ::csce438::SyncRequest* request, ::grpc::ServerAsyncResponseWriter< ::csce438::SyncReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SyncFollowers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SyncFollowers() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SyncFollowers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncFollowers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncFollowers(::grpc::ServerContext* context, ::csce438::SyncRequest* request, ::grpc::ServerAsyncResponseWriter< ::csce438::SyncReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SyncTimeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SyncTimeline() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SyncTimeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTimeline(::grpc::ServerContext* /*context*/, const ::csce438::timelineRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncTimeline(::grpc::ServerContext* context, ::csce438::timelineRequest* request, ::grpc::ServerAsyncResponseWriter< ::csce438::SyncReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateMaster : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateMaster() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateMaster() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMaster(::grpc::ServerContext* /*context*/, const ::csce438::MasterInfo* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateMaster(::grpc::ServerContext* context, ::csce438::MasterInfo* request, ::grpc::ServerAsyncResponseWriter< ::csce438::SyncReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SyncUsers<WithAsyncMethod_SyncFollowers<WithAsyncMethod_SyncTimeline<WithAsyncMethod_UpdateMaster<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SyncUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SyncUsers() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::csce438::SyncRequest, ::csce438::SyncReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response) { return this->SyncUsers(context, request, response); }));}
    void SetMessageAllocatorFor_SyncUsers(
        ::grpc::MessageAllocator< ::csce438::SyncRequest, ::csce438::SyncReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::csce438::SyncRequest, ::csce438::SyncReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SyncUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncUsers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SyncUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SyncFollowers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SyncFollowers() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::csce438::SyncRequest, ::csce438::SyncReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::csce438::SyncRequest* request, ::csce438::SyncReply* response) { return this->SyncFollowers(context, request, response); }));}
    void SetMessageAllocatorFor_SyncFollowers(
        ::grpc::MessageAllocator< ::csce438::SyncRequest, ::csce438::SyncReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::csce438::SyncRequest, ::csce438::SyncReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SyncFollowers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncFollowers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SyncFollowers(
      ::grpc::CallbackServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SyncTimeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SyncTimeline() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::csce438::timelineRequest, ::csce438::SyncReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::csce438::timelineRequest* request, ::csce438::SyncReply* response) { return this->SyncTimeline(context, request, response); }));}
    void SetMessageAllocatorFor_SyncTimeline(
        ::grpc::MessageAllocator< ::csce438::timelineRequest, ::csce438::SyncReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::csce438::timelineRequest, ::csce438::SyncReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SyncTimeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTimeline(::grpc::ServerContext* /*context*/, const ::csce438::timelineRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SyncTimeline(
      ::grpc::CallbackServerContext* /*context*/, const ::csce438::timelineRequest* /*request*/, ::csce438::SyncReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateMaster : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateMaster() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::csce438::MasterInfo, ::csce438::SyncReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::csce438::MasterInfo* request, ::csce438::SyncReply* response) { return this->UpdateMaster(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateMaster(
        ::grpc::MessageAllocator< ::csce438::MasterInfo, ::csce438::SyncReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::csce438::MasterInfo, ::csce438::SyncReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateMaster() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMaster(::grpc::ServerContext* /*context*/, const ::csce438::MasterInfo* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateMaster(
      ::grpc::CallbackServerContext* /*context*/, const ::csce438::MasterInfo* /*request*/, ::csce438::SyncReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SyncUsers<WithCallbackMethod_SyncFollowers<WithCallbackMethod_SyncTimeline<WithCallbackMethod_UpdateMaster<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SyncUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SyncUsers() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SyncUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncUsers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SyncFollowers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SyncFollowers() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SyncFollowers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncFollowers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SyncTimeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SyncTimeline() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SyncTimeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTimeline(::grpc::ServerContext* /*context*/, const ::csce438::timelineRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateMaster : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateMaster() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateMaster() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMaster(::grpc::ServerContext* /*context*/, const ::csce438::MasterInfo* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SyncUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SyncUsers() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SyncUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncUsers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncUsers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SyncFollowers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SyncFollowers() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SyncFollowers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncFollowers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncFollowers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SyncTimeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SyncTimeline() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SyncTimeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTimeline(::grpc::ServerContext* /*context*/, const ::csce438::timelineRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSyncTimeline(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateMaster : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateMaster() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_UpdateMaster() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMaster(::grpc::ServerContext* /*context*/, const ::csce438::MasterInfo* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateMaster(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SyncUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SyncUsers() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SyncUsers(context, request, response); }));
    }
    ~WithRawCallbackMethod_SyncUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncUsers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SyncUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SyncFollowers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SyncFollowers() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SyncFollowers(context, request, response); }));
    }
    ~WithRawCallbackMethod_SyncFollowers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncFollowers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SyncFollowers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SyncTimeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SyncTimeline() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SyncTimeline(context, request, response); }));
    }
    ~WithRawCallbackMethod_SyncTimeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SyncTimeline(::grpc::ServerContext* /*context*/, const ::csce438::timelineRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SyncTimeline(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateMaster : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateMaster() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateMaster(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateMaster() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMaster(::grpc::ServerContext* /*context*/, const ::csce438::MasterInfo* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateMaster(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SyncUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SyncUsers() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::csce438::SyncRequest, ::csce438::SyncReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::csce438::SyncRequest, ::csce438::SyncReply>* streamer) {
                       return this->StreamedSyncUsers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SyncUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SyncUsers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSyncUsers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::csce438::SyncRequest,::csce438::SyncReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SyncFollowers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SyncFollowers() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::csce438::SyncRequest, ::csce438::SyncReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::csce438::SyncRequest, ::csce438::SyncReply>* streamer) {
                       return this->StreamedSyncFollowers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SyncFollowers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SyncFollowers(::grpc::ServerContext* /*context*/, const ::csce438::SyncRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSyncFollowers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::csce438::SyncRequest,::csce438::SyncReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SyncTimeline : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SyncTimeline() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::csce438::timelineRequest, ::csce438::SyncReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::csce438::timelineRequest, ::csce438::SyncReply>* streamer) {
                       return this->StreamedSyncTimeline(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SyncTimeline() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SyncTimeline(::grpc::ServerContext* /*context*/, const ::csce438::timelineRequest* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSyncTimeline(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::csce438::timelineRequest,::csce438::SyncReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateMaster : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateMaster() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::csce438::MasterInfo, ::csce438::SyncReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::csce438::MasterInfo, ::csce438::SyncReply>* streamer) {
                       return this->StreamedUpdateMaster(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateMaster() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateMaster(::grpc::ServerContext* /*context*/, const ::csce438::MasterInfo* /*request*/, ::csce438::SyncReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateMaster(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::csce438::MasterInfo,::csce438::SyncReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SyncUsers<WithStreamedUnaryMethod_SyncFollowers<WithStreamedUnaryMethod_SyncTimeline<WithStreamedUnaryMethod_UpdateMaster<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SyncUsers<WithStreamedUnaryMethod_SyncFollowers<WithStreamedUnaryMethod_SyncTimeline<WithStreamedUnaryMethod_UpdateMaster<Service > > > > StreamedService;
};

}  // namespace csce438


#endif  // GRPC_synchronizer_2eproto__INCLUDED
